# Generated by Django 6.0.3 on 2026-03-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('responsibilities', models.TextField()),
                ('education', models.TextField()),
                ('vacancies', models.PositiveIntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_type', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('remote_job', 'Remote Job')], max_length=20)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('opening_date', models.DateField()),
                ('deadline', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recruiterprofile')),
            ],
        ),
    ]
