# Generated by Django 6.0.3 on 2026-03-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profile_picture_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_image',
            new_name='profile_pic',
        ),
    ]
